### ISSUE TITLE
Focusable used instead of Tabindex for SVGs

### ISSUE THREAD

**Issue by thezacharytaylor** [a11yphant/a11yphant#189]
**Describe the bug**
Button 09 advocates the use of `focusable`.

**To Reproduce**
Read the hint in Button 09 and try to use `tabindex="-1"` over the suggested `focusable="false"`

**Expected behaviour**
`tabindex="-1"` should pass.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.6.3
 - Arc Version 1.21.3 

**Additional context**
SVG 1.2, 2008, did introduce this, but since 2018 and SVG 2.0 tabindex has been supported and SVG 2.0 does not list focusable. 
https://www.w3.org/TR/SVGTiny12/interact.html#focusable-attr
https://www.w3.org/TR/SVG2/struct.html#tabindexattribute

I did locate this in the SVG2 editors draft:
https://www.w3.org/TR/SVG2/interact.html#Focus
"For compatibility with content that used the SVG Tiny 1.2 `focusable` attribute, user agents should treat an element with a value of `true` for that attribute as focusable. **In new content, authors should either omit the focusable attribute or use it only in combination with a corresponding** `tabindex` **value of** `0`**."**

That said, SVG2 is still in candidate recommendation. So I consulted caniuse and found these results:
https://caniuse.com/?search='focusable'%20attribute
https://caniuse.com/?search=svg%20attributes
https://caniuse.com/mdn-svg_attributes_core_tabindex

I cannot find anything to suggest the use of focusable over tabindex. However, if there is a valid reason, hopefully not relating to Internet Explorer (haha!), then can we add it to that lesson?

**Comment by lucapircher** [comment]
Hi @thezacharytaylor,
again thanks for reporting this! We will look into this, but I think this was an oversight on our end. I can assure you that Internet Explorer was not the cause for using the `focusable` attribute haha
