### ISSUE TITLE
The use of the term Hearing Impaired is problematic

### ISSUE THREAD

**Issue by thezacharytaylor** [a11yphant/a11yphant#190]
**Describe the bug**
Web Accessibility Intro Level 05 uses the term hearing impairment, twice. This is a problematic term as the deaf and hard of hearing community typically see it as a slur.

**Expected behaviour**
For the question to instead be something along the lines of: "Which assistive devices are often used by people with hearing loss (e.g. Deaf or hard of hearing)?" Alternatively the term deafness could still be used, or even deaf. I did swap them to make the capital D make more sense grammatically and because the two are typically pronounced alphabetically.

**Screenshots**
![Screenshot 2024-01-09 at 1 40 23 PM](https://github.com/a11yphant/a11yphant/assets/21206039/ebe66560-b691-4d17-9a5a-a3ed457f1a4b)

**Additional context**
I am unaffiliated with this site, but this might be a good start if one is looking to read up (or needing a Google search base) on this issue:
https://nagish.com/post/is-hearing-impaired-offensive-term

**Comment by lucapircher** [comment]
Hi @thezacharytaylor,
thanks a lot for bringing this to our attention! We were not aware this term is seen as a slur.
I've just updated the wording with your proposal.
